server:
  port: 8085
spring:
  application:
    name: admin-service
  boot:
    admin:
      client:
        instance:
          service-host-type: ip
      discovery:
        enabled: true
        ignored-services: admin-service
        converter:
          management-context-path: "/actuator"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.server-url}/realms/${keycloak.realm}
      client:
        provider:
          keycloak:
            issuer-uri: ${keycloak.server-url}/realms/${keycloak.realm}
        registration:
          keycloak:
            client-id: ${keycloak.admin-client-id}
            client-secret: ${keycloak.admin-client-secret}
            authorization-grant-type: client_credentials
            scope:
              - metrics
          discovery:
            provider: keycloak
            client-id: ${keycloak.admin-client-id}
            client-secret: ${keycloak.admin-client-secret}
            authorization-grant-type: client_credentials
            scope:
              - discovery
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    prefer-ip-address: true
  client:
    service-url:
      registryFetchIntervalSeconds: 5
      defaultZone: ${eureka.server-url}/eureka/