spring:
  thymeleaf:
    enabled: false
  application:
    name: eureka-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.server-url}/realms/${keycloak.realm}
      client:
        provider:
          keycloak:
            user-name-attribute: preferred_username
            issuer-uri: ${keycloak.server-url}/realms/${keycloak.realm}
        registration:
          keycloak:
            client-id: ${keycloak.eureka-client-id}
            client-secret: ${keycloak.eureka-client-secret}
            authorization-grant-type: client_credentials
          metrics:
            provider: keycloak
            client-id: ${keycloak.eureka-client-id}
            client-secret: ${keycloak.eureka-client-secret}
            authorization-grant-type: client_credentials
            scope:
              - metrics
server:
  port: 8761
eureka:
  instance:
    hostname: ${eureka.hostname}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
      probes:
        enabled: true